export const products = [
  {
    id: 1,
    name: "Boys Best Combo",
    short: "2 Formal Pants + Premium Shoes + Watch",
    mrp: 4199,
    price: 999,
    advance: 499,
    cod: 500,
    badge: "MEGA SALE",
    image: "/products/product-1.jpg",
  },

  {
    id: 2,
    name: "Boys Premium Accessories Combo",
    short: "Watch + Chasma + Bracelet + Locket + Purse",
    mrp: 2599,
    price: 766,
    advance: 366,
    cod: 400,
    badge: "HOT DEAL",
    image: "/products/product-2.jpg",
  },

  {
    id: 3,
    name: "Formal Premium Combo",
    short: "2 Shirts + Pants + Shoes + Watch",
    mrp: 3899,
    price: 999,
    advance: 499,
    cod: 500,
    badge: "BEST SELLER",
    image: "/products/product-3.jpg",
  },

  {
    id: 4,
    name: "Men's Premium Fashion Combo",
    short: "Shirt + Jeans/Pant + Belt + Wallet + Sunglasses",
    mrp: 2999,
    price: 899,
    advance: 399,
    cod: 500,
    badge: "TRENDING",
    image: "/products/product-4.jpg",
  },

  {
    id: 5,
    name: "Royal Accessories Combo",
    short: "Watch + Bracelet + Chain + Wallet + Sunglasses",
    mrp: 2499,
    price: 799,
    advance: 399,
    cod: 400,
    badge: "ROYAL DEAL",
    image: "/products/product-5.jpg",
  },

  {
    id: 6,
    name: "Complete Men's Style Combo",
    short: "Shirt + Pant + Shoes + Watch + Belt + Wallet",
    mrp: 4499,
    price: 1199,
    advance: 599,
    cod: 600,
    badge: "PREMIUM",
    image: "/products/product-6.jpg",
  },
];
